### PR TITLE
Add Python notebooks

### PR DESCRIPTION
**Pull request by afuetterer**
In this PR the following changes are introduced:

- [x] add Jupyter notebooks, written in Python
  - [x] use case 1
  - [x] use case 2
  - [x] use case 3
- [x] notebooks are prefixed with 01, 02, 03 as per the use case numbering in README
- [x] add Heinz-Alexander Fütterer to the README as contributor

The Python notebooks:
- [x] give credit to Dorothea Strecker as author of the R notebooks
- [x] make use of black and isort for code quality (for notebooks: line-length=120)
- [x]  contain output from a single "run all cells"

### CODE REVIEW

**Comment by afuetterer** [comment]
I named the notebooks with prefixes 01, 02, 03, according to the numbering in the README. Is that alright with you?

**Comment by afuetterer** [comment]
Should the API calls the re3data API ("for url in urls") be rate limited? There are ca. 2500 API calls in 5 minutes. This is not so polite to the service. The R notebooks make API calls for each url as well, how long does one run usually take?

I can add rate limiting by either adding a `time.sleep()` to every API call or just allowing X requests per minute. What do you think?

**Comment by dorothearrr** [comment]
> Should the API calls the re3data API ("for url in urls") be rate limited? There are ca. 2500 API calls in 5 minutes. This is not so polite to the service. The R notebooks make API calls for each url as well, how long does one run usually take?
> 
> I can add rate limiting by either adding a `time.sleep()` to every API call or just allowing X requests per minute. What do you think?

In the R notebooks, the 2500 API calls typically take around 5.3 minutes. You are right, that is not very polite... I will talk to the developer about rate limiting and get back to you!

**Comment by afuetterer** [comment]
> In the R notebooks, the 2500 API calls typically take around 5.3 minutes. You are right, that is not very polite... I will talk to the developer about rate limiting and get back to you!

Thanks for your input. I will finish the PR then, running the API calls without pausing.
If re3data decides to add rate limiting, we can adapt both the R and Python notebooks. Alright?

**Comment by afuetterer** [comment]
I added titles to the plots in use case 2 and 3 to indicate the date the analysis was run and the number of repositories.
Especially if repositories are dropped (e.g. due to having no API in use case 3) it might be hard to make sense of the numbers in the plot. 538 of _n_ repositories provide a REST api. I added this number to the title. What do you think?

1. https://github.com/afuetterer/using_the_re3data_API/blob/add-python-notebooks/examples-python/01_re3data_API_medical_research_community.ipynb
2. https://github.com/afuetterer/using_the_re3data_API/blob/add-python-notebooks/examples-python/02_re3data_API_certification_by_type.ipynb
3. https://github.com/afuetterer/using_the_re3data_API/blob/add-python-notebooks/examples-python/02_re3data_API_certification_by_type.ipynb

If you agree, I will clean up the notebooks and can review the PR.

**Comment by dorothearrr** [comment]
> I added titles to the plots in use case 2 and 3 to indicate the date the analysis was run and the number of repositories.

Good point, that information provides valuable context. I will implement that in the R notebooks as well.

**Comment by afuetterer** [comment]
Thanks for adapting your R notebooks.

I saw that we had differing counts in the plots in use case 2 and 3. I dug a bit into the differences in our dataframes, that were counted and plotted. Finally I found my "mistake", I needed to add a `drop_duplicates()`call.

The problem was that a had duplicated rows in my dataframes. There was something I did not foresee, that has to do with data in the API responses.

The `type` of a repository is defined as follows:
> type is allowed 1-n

> Controlled vocabulary
> Allowed values:
> disciplinary
> institutional
> other

So far thats good. But this seemingly also allows to add the same type multiple times? This makes no sense to me, but still it is done.

See: 
- https://www.re3data.org/repository/r3d100011997
> Repository type(s):
>    disciplinary
>    disciplinary

- https://www.re3data.org/repository/r3d100012460

> Repository type(s)
>    disciplinary
>    disciplinary

This oddity is in the underlying data. But I still fixed my way of counting.

**Comment by dorothearrr** [comment]
> My dataframe before plotting has these dimensions (1895, 5) vs. yours has (1832, 5). There is a difference of 63 rows. There might be a bug in your function to gather the APIs?

Thank you for pointing this out!
I updated the extraction function in the R implementation of example 3. The resulting data frame now has 1897 rows (likely, the Editorial Team added two APIs in the meantime).
In addition, I deduplicated the API types for the bar chart, so that each API type is counted only once per repository. That is how API types are counted in the re3data GUI and on the [metrics page](https://www.re3data.org/metrics/apis), and it might avoid confusion. What do you think?

**Comment by afuetterer** [comment]
Thanks. I can adapt the Python notebook 3 as well.

This deduplication step is done for the metrics page, alright. But does it make sense?

If I look at this page, it shows 4 APIs:
https://www.re3data.org/repository/r3d100010051

> Application programming interfaces (4)
> API type [SWORD](https://guides.dataverse.org/en/latest/api/sword.html)
> API type [other](https://guides.dataverse.org/en/latest/api/dataaccess.html)
> API type [other](https://guides.dataverse.org/en/latest/api/native-api.html)
> API type [other](https://guides.dataverse.org/en/4.2/api/search.html)

Should this be counted as SWORD: 1, other: 3 or SWORD: 1 and other: 1? I am not sure.

Go for deduplication?

**Comment by dorothearrr** [comment]
> Go for deduplication?

I would say so. Both ways of counting are valid, they just highlight different aspects. For consistency, I think it is best to stick with the approach used on the metrics page.

**Pull request merged**
